version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: example
  redis:
    image: "redis:latest"
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  api:
    build :
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      #this puts a block on this file in the image
      - /app/node_modules
      # this says map anything else from the server folder and put it into the folder app in the image
      - ./server:/app
    environment:
      # point at out own version of redis as the host
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=example
      - PGPORT=5432
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379